// Move Better (human) topic-suggestion bank.
// Built from PNW chiropractic search patterns, common conditions at Move
// Better, and regional activity-specific injuries.
//
// priority: 'high' = very high patient search volume, 'medium' = solid volume,
//           'low' = niche but relevant to Move Better's patient base.

export const TOPIC_SUGGESTIONS = [
  // ── Spine & Core ──────────────────────────────────────────────────────────
  {
    topic: 'Low back pain',
    category: 'Spine & Core',
    priority: 'high',
    keywords: ['low back', 'lower back', 'lumbar'],
    pnwNote: '#1 searched chiropractic condition nationally and in Oregon',
  },
  {
    topic: 'Neck pain',
    category: 'Spine & Core',
    priority: 'high',
    keywords: ['neck pain', 'cervical'],
    pnwNote: 'High volume — aggravated by desk work and driving',
  },
  {
    topic: 'Sciatica',
    category: 'Spine & Core',
    priority: 'high',
    keywords: ['sciatica', 'sciatic'],
    pnwNote: 'Consistently top-5 searched pain condition',
  },
  {
    topic: 'Disc herniation',
    category: 'Spine & Core',
    priority: 'high',
    keywords: ['disc herniation', 'herniated disc', 'bulging disc', 'disc bulge'],
    pnwNote: 'Patients often search this after an MRI diagnosis',
  },
  {
    topic: 'Text neck & posture',
    category: 'Spine & Core',
    priority: 'high',
    keywords: ['text neck', 'posture', 'forward head'],
    pnwNote: "Portland's large tech workforce drives high search volume",
  },
  {
    topic: 'Work-from-home back & neck pain',
    category: 'Spine & Core',
    priority: 'high',
    keywords: ['work from home', 'desk pain', 'ergonomics', 'home office'],
    pnwNote: 'Post-2020 surge; Portland has one of the highest remote-work rates in the US',
  },
  {
    topic: 'SI joint pain',
    category: 'Spine & Core',
    priority: 'medium',
    keywords: ['si joint', 'sacroiliac', 'sacrum'],
    pnwNote: 'Common in runners and during/after pregnancy',
  },
  {
    topic: 'Mid-back pain',
    category: 'Spine & Core',
    priority: 'medium',
    keywords: ['mid back', 'mid-back', 'thoracic', 'upper back'],
    pnwNote: 'Often overlooked — frequently caused by breathing dysfunction',
  },
  {
    topic: 'Spinal stenosis',
    category: 'Spine & Core',
    priority: 'medium',
    keywords: ['stenosis', 'spinal stenosis'],
    pnwNote: 'Pacific Northwest has above-average spinal procedure rates',
  },
  {
    topic: 'Scoliosis',
    category: 'Spine & Core',
    priority: 'medium',
    keywords: ['scoliosis'],
    pnwNote: 'Parents frequently search for non-surgical options for teens',
  },

  // ── Head & Nervous System ─────────────────────────────────────────────────
  {
    topic: 'Headaches & migraines',
    category: 'Head & Nervous System',
    priority: 'high',
    keywords: ['headache', 'migraine'],
    pnwNote: 'Top-3 searched chiropractic condition; pressure changes in PNW worsen migraines',
  },
  {
    topic: 'Concussion recovery',
    category: 'Head & Nervous System',
    priority: 'medium',
    keywords: ['concussion', 'post-concussion', 'tbi'],
    pnwNote: 'High relevance for Portland contact sports — soccer, rugby, mountain biking',
  },
  {
    topic: 'TMJ & jaw pain',
    category: 'Head & Nervous System',
    priority: 'medium',
    keywords: ['tmj', 'jaw pain', 'temporomandibular'],
    pnwNote: 'Patients struggle to find providers — strong content opportunity',
  },
  {
    topic: 'Vertigo & dizziness',
    category: 'Head & Nervous System',
    priority: 'medium',
    keywords: ['vertigo', 'dizziness', 'bppv'],
    pnwNote: 'Patients rarely know chiropractic can help — high discovery potential',
  },
  {
    topic: 'Numbness & tingling',
    category: 'Head & Nervous System',
    priority: 'medium',
    keywords: ['numbness', 'tingling', 'neuropathy', 'pins and needles'],
    pnwNote: 'Frequently misattributed — content clarifying root causes drives trust',
  },

  // ── Shoulder & Upper Extremity ────────────────────────────────────────────
  {
    topic: 'Shoulder pain',
    category: 'Shoulder & Upper Extremity',
    priority: 'high',
    keywords: ['shoulder pain', 'shoulder impingement'],
    pnwNote: 'Climbing, kayaking, and swimming all stress the shoulder heavily in PNW',
  },
  {
    topic: 'Rotator cuff injury',
    category: 'Shoulder & Upper Extremity',
    priority: 'medium',
    keywords: ['rotator cuff', 'rotator'],
    pnwNote: 'Patients actively searching for non-surgical alternatives',
  },
  {
    topic: 'Frozen shoulder',
    category: 'Shoulder & Upper Extremity',
    priority: 'medium',
    keywords: ['frozen shoulder', 'adhesive capsulitis'],
    pnwNote: 'High frustration condition — clear content about recovery wins trust',
  },
  {
    topic: 'Rock climbing shoulder & elbow injuries',
    category: 'Shoulder & Upper Extremity',
    priority: 'high',
    keywords: ['climbing', 'rock climbing', 'climber'],
    pnwNote: "Smith Rock is one of the US's top climbing destinations — huge local audience",
  },
  {
    topic: 'Tennis elbow',
    category: 'Shoulder & Upper Extremity',
    priority: 'medium',
    keywords: ['tennis elbow', 'lateral epicondylitis', 'lateral epicondyle'],
    pnwNote: 'Common in cyclists, climbers, and desk workers',
  },
  {
    topic: "Golfer's elbow",
    category: 'Shoulder & Upper Extremity',
    priority: 'low',
    keywords: ["golfer's elbow", 'golfers elbow', 'medial epicondylitis'],
    pnwNote: 'Less searched but relevant for climbing and throwing sports',
  },
  {
    topic: 'Carpal tunnel syndrome',
    category: 'Shoulder & Upper Extremity',
    priority: 'medium',
    keywords: ['carpal tunnel', 'wrist pain', 'wrist numbness'],
    pnwNote: 'Portland tech workforce — strong search demand for non-surgical options',
  },

  // ── Hip & Lower Extremity ─────────────────────────────────────────────────
  {
    topic: 'Knee pain',
    category: 'Hip & Lower Extremity',
    priority: 'high',
    keywords: ['knee pain', 'knee injury', 'runner\'s knee', 'patellar'],
    pnwNote: "Runners, cyclists, and hikers all deal with knee issues — Portland's #1 sports injury",
  },
  {
    topic: 'Hip pain & hip flexor tightness',
    category: 'Hip & Lower Extremity',
    priority: 'medium',
    keywords: ['hip pain', 'hip flexor', 'hip tightness', 'hip impingement'],
    pnwNote: 'Desk workers and runners alike — broad audience',
  },
  {
    topic: 'IT band syndrome',
    category: 'Hip & Lower Extremity',
    priority: 'high',
    keywords: ['it band', 'iliotibial', 'itbs'],
    pnwNote: 'Trail running capital — Forest Park runners are prime audience',
  },
  {
    topic: 'Piriformis syndrome',
    category: 'Hip & Lower Extremity',
    priority: 'medium',
    keywords: ['piriformis', 'deep gluteal'],
    pnwNote: 'Often confused with sciatica — high content discovery opportunity',
  },
  {
    topic: 'Plantar fasciitis',
    category: 'Hip & Lower Extremity',
    priority: 'high',
    keywords: ['plantar fasciitis', 'heel pain', 'plantar'],
    pnwNote: 'Year-round running culture keeps this consistently high-searched',
  },
  {
    topic: 'Achilles tendinitis',
    category: 'Hip & Lower Extremity',
    priority: 'medium',
    keywords: ['achilles', 'achilles tendinitis', 'achilles tendinopathy'],
    pnwNote: 'Trail runners and cyclists — returning to activity after injury',
  },
  {
    topic: 'Ankle sprain & instability',
    category: 'Hip & Lower Extremity',
    priority: 'medium',
    keywords: ['ankle sprain', 'ankle instability', 'ankle pain'],
    pnwNote: 'Hiking on uneven PNW terrain — repeated ankle sprains are common',
  },
  {
    topic: 'Shin splints',
    category: 'Hip & Lower Extremity',
    priority: 'medium',
    keywords: ['shin splints', 'medial tibial', 'shin pain'],
    pnwNote: 'New runners starting out on Portland paths',
  },

  // ── PNW Sports & Activity ─────────────────────────────────────────────────
  {
    topic: 'Trail running injuries',
    category: 'PNW Sports & Activity',
    priority: 'high',
    keywords: ['trail running', 'trail run', 'ultra running'],
    pnwNote: 'Forest Park hosts more trail miles than Central Park — massive local audience',
  },
  {
    topic: 'Cycling & mountain biking injuries',
    category: 'PNW Sports & Activity',
    priority: 'high',
    keywords: ['cycling', 'cyclist', 'mountain biking', 'bike'],
    pnwNote: 'Portland is consistently ranked a top US cycling city',
  },
  {
    topic: 'Skiing & snowboard injuries',
    category: 'PNW Sports & Activity',
    priority: 'high',
    keywords: ['skiing', 'snowboard', 'ski injury', 'mt hood'],
    pnwNote: 'Mt. Hood has year-round skiing — winter injuries flood clinics Jan–Mar',
  },
  {
    topic: 'Hiking & backpacking injuries',
    category: 'PNW Sports & Activity',
    priority: 'medium',
    keywords: ['hiking', 'backpacking', 'hiker', 'trail'],
    pnwNote: 'Columbia River Gorge, Mt Hood, and the Cascades bring year-round hikers',
  },
  {
    topic: 'Swimming & paddle sports shoulder',
    category: 'PNW Sports & Activity',
    priority: 'low',
    keywords: ['swimming', 'kayaking', 'paddleboarding', 'swim shoulder'],
    pnwNote: 'Columbia River and coastal access — active paddling community',
  },
  {
    topic: 'Youth & youth sports injuries',
    category: 'PNW Sports & Activity',
    priority: 'medium',
    keywords: ['youth', 'kids', 'pediatric', 'young athlete', 'youth sports'],
    pnwNote: 'Parents searching for safe, conservative care for children',
  },

  // ── Special Populations ───────────────────────────────────────────────────
  {
    topic: 'Prenatal & pregnancy pain',
    category: 'Special Populations',
    priority: 'high',
    keywords: ['prenatal', 'pregnancy', 'pregnant'],
    pnwNote: 'Clinics report strong demand — patients actively seek chiropractic during pregnancy',
  },
  {
    topic: 'Postpartum recovery',
    category: 'Special Populations',
    priority: 'medium',
    keywords: ['postpartum', 'post-partum', 'after birth', 'new mom'],
    pnwNote: "Underserved topic with growing search interest — Move Better's content can own this",
  },
  {
    topic: 'Aging & staying active over 50',
    category: 'Special Populations',
    priority: 'medium',
    keywords: ['aging', 'over 50', 'senior', 'older athlete', 'masters'],
    pnwNote: "PNW's active aging population wants to keep hiking, biking, and skiing",
  },

  // ── Chronic & Systemic ────────────────────────────────────────────────────
  {
    topic: 'Chronic pain management',
    category: 'Chronic & Systemic',
    priority: 'high',
    keywords: ['chronic pain', 'chronic'],
    pnwNote: 'Oregon has above-average opioid awareness — patients seek alternatives',
  },
  {
    topic: 'Whiplash & car accident recovery',
    category: 'Chronic & Systemic',
    priority: 'high',
    keywords: ['whiplash', 'car accident', 'auto accident', 'mva', 'motor vehicle'],
    pnwNote: 'Portland traffic — high MVA volume with patients unsure where to go',
  },
  {
    topic: 'Arthritis & joint pain',
    category: 'Chronic & Systemic',
    priority: 'medium',
    keywords: ['arthritis', 'osteoarthritis', 'joint pain', 'degenerative'],
    pnwNote: 'Aging active population looking to avoid surgery and stay mobile',
  },
  {
    topic: 'Fibromyalgia',
    category: 'Chronic & Systemic',
    priority: 'medium',
    keywords: ['fibromyalgia', 'fibro'],
    pnwNote: 'Patients feel dismissed by conventional medicine — chiropractic content builds trust',
  },
  {
    topic: 'Stress, tension & pain connection',
    category: 'Chronic & Systemic',
    priority: 'medium',
    keywords: ['stress', 'tension', 'anxiety', 'stress and pain'],
    pnwNote: 'Tech industry stress culture in Portland; patients seeking mind-body approaches',
  },
  {
    topic: 'Movement & strength for pain prevention',
    category: 'Chronic & Systemic',
    priority: 'medium',
    keywords: ['strength', 'prevention', 'movement training', 'rehab exercise'],
    pnwNote: 'High-value topic aligning directly with Move Better philosophy',
  },

  // ── Physical Therapy & Rehabilitation ────────────────────────────────────
  {
    topic: 'Injury rehab & return to sport',
    category: 'Physical Therapy & Rehab',
    priority: 'high',
    keywords: ['rehab', 'rehabilitation', 'return to sport', 'return to activity'],
    pnwNote: 'Active PNW population wants to get back to their sport — not just be pain-free',
  },
  {
    topic: 'Exercise prescription for pain relief',
    category: 'Physical Therapy & Rehab',
    priority: 'high',
    keywords: ['exercise prescription', 'therapeutic exercise', 'corrective exercise', 'rehab exercises'],
    pnwNote: 'Patients searching for specific exercises — high content discovery potential',
  },
  {
    topic: 'Soft tissue therapy & myofascial release',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['soft tissue', 'myofascial', 'trigger point', 'graston', 'iastm', 'instrument assisted'],
    pnwNote: 'Differentiates Move Better from purely adjustment-focused clinics',
  },
  {
    topic: 'Dry needling',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['dry needling', 'trigger point needling', 'intramuscular stimulation'],
    pnwNote: 'Growing awareness — often confused with acupuncture, content can clarify',
  },
  {
    topic: 'Shockwave therapy',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['shockwave', 'shockwave therapy', 'eswt', 'extracorporeal'],
    pnwNote: 'Move Better offers this — very few clinics do, strong content differentiation',
  },
  {
    topic: 'Acupuncture for pain & recovery',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['acupuncture', 'sports acupuncture', 'acupuncture pain'],
    pnwNote: 'Move Better offers this — patients want to know what acupuncture actually treats',
  },
  {
    topic: 'Core stability & functional movement',
    category: 'Physical Therapy & Rehab',
    priority: 'high',
    keywords: ['core stability', 'core strength', 'functional movement', 'movement patterns'],
    pnwNote: "Directly ties to Move Better's Movement Paradigm — breathing, bracing, hinging",
  },
  {
    topic: 'Hip strength & glute activation',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['hip strength', 'glute activation', 'glutes', 'hip stability'],
    pnwNote: 'Root cause of many lower extremity issues — core to Move Better philosophy',
  },
  {
    topic: 'Breathing mechanics & diaphragm training',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['breathing mechanics', 'diaphragm', 'breathing paradigm', 'belly breathing'],
    pnwNote: "Move Better's Breathing Paradigm — unique angle very few clinics cover in content",
  },
  {
    topic: 'Load management & overuse injury prevention',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['load management', 'overuse injury', 'overtraining', 'training load'],
    pnwNote: 'Endurance athletes in PNW — cyclists, runners, and triathletes frequently overtrain',
  },
  {
    topic: 'Post-surgical rehabilitation',
    category: 'Physical Therapy & Rehab',
    priority: 'medium',
    keywords: ['post-surgical', 'post surgery', 'after surgery', 'surgical rehab'],
    pnwNote: 'Patients searching for conservative care after or instead of surgery',
  },
]
